import datetime as dt
ts = dt.datetime.now()
print(ts)
print(ts.year)
print(ts.month, ts.day)
print(ts.day)
print(ts.hour)
print(ts.minute)
print(ts.second)
print(ts.microsecond)
print(ts.astimezone())
print(ts.weekday())
